### ISSUE TITLE
reset password

### ISSUE THREAD

**Issue by alahammad** [moloch--/RootTheBox#381] opened 2020-06-07 17:30 UTC
Reset password feature is very important, and also players forget password or username, 
can we add sending reset password using fastmail, or other free service for example :

https://alexwlchan.net/2016/05/python-smtplib-and-fastmail/

**Comment by jeffg2k** [comment] 2020-06-08 13:57
Good info - Can you add this to the existing issue request #232

**Comment by jeffg2k** [comment] 2020-06-11 23:15
Duplicate of #232

**Closed by jeffg2k** 2020-06-11 23:15 UTC
