### ISSUE TITLE
Export XML 404 Error

### ISSUE THREAD

**Issue by jeremytourville** [moloch--/RootTheBox#334] opened 2020-01-24 03:07 UTC
I did the `docker-compose build` and tested it without even trying the `--debug` parameter.  That fixed the issue.  Don't know why but, hey I'll take the win just the same.  Export works now!  :-)

_Originally posted by @jeremytourville in https://github.com/moloch--/RootTheBox/issues/333#issuecomment-577961584_

**Comment by jeremytourville** [comment] 2020-01-24 03:08
OK, I spoke too quickly.  Here is the output from the debug

```
rtb_1       |     HTTPServerRequest(protocol='http', host='docker:8888', method='POST', uri='/admin/export/xml', version='HTTP/1.1', remote_ip='172.30.50.18')
rtb_1       |     Traceback (most recent call last):
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1063, in _escape_cdata
rtb_1       |         if "&" in text:
rtb_1       |     TypeError: a bytes-like object is required, not 'str'
rtb_1       |
rtb_1       |     During handling of the above exception, another exception occurred:
rtb_1       |
rtb_1       |     Traceback (most recent call last):
rtb_1       |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1697, in _execute
rtb_1       |         result = method(*self.path_args, **self.path_kwargs)
rtb_1       |       File "/opt/rtb/libs/SecurityDecorators.py", line 77, in wrapper
rtb_1       |         return method(self, *args, **kwargs)
rtb_1       |       File "/opt/rtb/libs/SecurityDecorators.py", line 46, in wrapper
rtb_1       |         return method(self, *args, **kwargs)
rtb_1       |       File "/opt/rtb/libs/SecurityDecorators.py", line 108, in wrapper
rtb_1       |         return method(self, *args, **kwargs)
rtb_1       |       File "/opt/rtb/handlers/AdminHandlers/AdminGameHandlers.py", line 486, in post
rtb_1       |         xml_dom = defusedxml.minidom.parseString(ET.tostring(root))
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1133, in tostring
rtb_1       |         ElementTree(element).write(stream, encoding,
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 772, in write
rtb_1       |         serialize(write, self._root, qnames, namespaces,
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 937, in _serialize_xml
rtb_1       |         _serialize_xml(write, e, qnames, None,
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 937, in _serialize_xml
rtb_1       |         _serialize_xml(write, e, qnames, None,
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 937, in _serialize_xml
rtb_1       |         _serialize_xml(write, e, qnames, None,
rtb_1       |       [Previous line repeated 2 more times]
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 935, in _serialize_xml
rtb_1       |         write(_escape_cdata(text))
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1071, in _escape_cdata
rtb_1       |         _raise_serialization_error(text)
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1053, in _raise_serialization_error
rtb_1       |         raise TypeError(
rtb_1       |     TypeError: cannot serialize b'0307c410ab05f0433d551a9a39bc8f7b' (type bytes)
rtb_1       | [E 200124 03:05:47 BaseHandlers:195] Request from 172.30.50.18 resulted in an error code 500:
rtb_1       |     Traceback (most recent call last):
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1063, in _escape_cdata
rtb_1       |         if "&" in text:
rtb_1       |     TypeError: a bytes-like object is required, not 'str'
rtb_1       |
rtb_1       |     During handling of the above exception, another exception occurred:
rtb_1       |
rtb_1       |     Traceback (most recent call last):
rtb_1       |       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1697, in _execute
rtb_1       |         result = method(*self.path_args, **self.path_kwargs)
rtb_1       |       File "/opt/rtb/libs/SecurityDecorators.py", line 77, in wrapper
rtb_1       |         return method(self, *args, **kwargs)
rtb_1       |       File "/opt/rtb/libs/SecurityDecorators.py", line 46, in wrapper
rtb_1       |         return method(self, *args, **kwargs)
rtb_1       |       File "/opt/rtb/libs/SecurityDecorators.py", line 108, in wrapper
rtb_1       |         return method(self, *args, **kwargs)
rtb_1       |       File "/opt/rtb/handlers/AdminHandlers/AdminGameHandlers.py", line 486, in post
rtb_1       |         xml_dom = defusedxml.minidom.parseString(ET.tostring(root))
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1133, in tostring
rtb_1       |         ElementTree(element).write(stream, encoding,
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 772, in write
rtb_1       |         serialize(write, self._root, qnames, namespaces,
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 937, in _serialize_xml
rtb_1       |         _serialize_xml(write, e, qnames, None,
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 937, in _serialize_xml
rtb_1       |         _serialize_xml(write, e, qnames, None,
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 937, in _serialize_xml
rtb_1       |         _serialize_xml(write, e, qnames, None,
rtb_1       |       [Previous line repeated 2 more times]
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 935, in _serialize_xml
rtb_1       |         write(_escape_cdata(text))
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1071, in _escape_cdata
rtb_1       |         _raise_serialization_error(text)
rtb_1       |       File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1053, in _raise_serialization_error
rtb_1       |         raise TypeError(
rtb_1       |     TypeError: cannot serialize b'0307c410ab05f0433d551a9a39bc8f7b' (type bytes)
rtb_1       |
rtb_1       | [E 200124 03:05:47 web:2242] 500 POST /admin/export/xml (172.30.50.18) 39.20ms
rtb_1       | [I 200124 03:05:47 web:2242] 101 GET /connect/notifications/updates (172.30.50.18) 0.91ms
```

**Comment by jeremytourville** [comment] 2020-01-24 03:20
Ok, so I am also noticing that the export only works after having performed a reset when there isn't any info loaded yet.  As soon as I add a box I get the error.

**Comment by jeffg2k** [comment] 2020-01-24 12:39
That's the garbage key again - doh, same issue as #326, which I thought I fixed on Jan 6, 2020 with commit https://github.com/moloch--/RootTheBox/commit/73013ba55af93eb0f62ae0605306c7c8b429f482.   

Can you double check your commit version - just want to make sure before I undo stuff.
`git log -1 --oneline`

Also, what is your host OS.  I'm running MacOS and maybe if I were on a different OS I could reproduce it.

Might have to put a try except on line 324 and try it both as a str and bytes.
I did a push of using bytes but then reverted the commit as using bytes caused me the error that your seeing.

**Comment by jeremytourville** [comment] 2020-01-24 21:35
My Docker host OS is Centos 7 running within Ovirt hypervisor  I can check the rest when I get home later.

**Comment by jeremytourville** [comment] 2020-01-25 15:57
It took me a minute but I found out you need to be inside the RTB directory when you run the command.  I didn't know that.  Anyhow - `5aa44e8 Scoreboard update after create team`

**Comment by jeffg2k** [comment] 2020-01-25 18:06
Good news - you're running an old version.  Your commit indicates you're last update was Dec 8th, 2019.  The fix was applied on Jan 6th, 2020.  Update your repo by running `git pull`.  Then update or rebuild your docker container.

**Comment by jeremytourville** [comment] 2020-01-27 00:26
How is this possible when I built the project on 1/22?  I thought when I did the initial `git clone` to build the project I would have gotten the latest.  Here is the result of my `git pull`  Does this look correct?  I need to get a better understanding of how git works and I am researching.  I come from a SysAdmin background and not a development one.  Sorry.  Could you share the commands needed to get this all updated properly?

```
[root@docker RootTheBox]# git pull
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (127/127), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 127 (delta 82), reused 101 (delta 65), pack-reused 0
Receiving objects: 100% (127/127), 1.62 MiB | 0 bytes/s, done.
Resolving deltas: 100% (82/82), completed with 42 local objects.
From git://github.com/moloch--/RootTheBox
   5aa44e8..a5b219c  master     -> origin/master
From git://github.com/moloch--/RootTheBox
 * [new tag]         3.3.5      -> 3.3.5
 * [new tag]         3.3.6      -> 3.3.6
Updating 5aa44e8..a5b219c
error: Your local changes to the following files would be overwritten by merge:
        Dockerfile
Please, commit your changes or stash them before you can merge.
Aborting

```

**Comment by jeffg2k** [comment] 2020-01-27 01:03
🤷‍♂️I have no idea how you would get an old version by using `git clone`.  
It's failing to update because you've made a change to Dockerfile and that file is updated in the pending updates.  It doesn't want to overwrite your changes.  You can discard or stash the change to Dockerfile.  There are 3 git options to undo the local changes you have:

> Discard all local changes, but save them for possible re-use later:
> `git stash`
> 
> Discarding local changes (permanently) to a file:
> `git checkout -- Dockerfile`
> 
> Discard all local changes to all files permanently:
> `git reset --hard`

Since I don't know if you've made changes to other files that are not in conflict, I'm going to suggest one of the first two.  Either stash all your current changes, or disgard the change on Dockerfile.  Then you should be able to run `git pull` successfully.
So, something like this should work.
```
git checout -- Dockerfile
git pull
```

**Comment by jeffg2k** [comment] 2020-01-27 01:39
If you like using a GUI, I've found this works well on Linux. https://github.com/shiftkey/desktop
For MacOS and Windows: https://desktop.github.com/

**Comment by jeremytourville** [comment] 2020-01-27 03:35
I ran through the commands as you suggested.  

```
[root@docker RootTheBox]# git stash
No local changes to save
[root@docker RootTheBox]# git checkout -- Dockerfile
[root@docker RootTheBox]# git reset --hard
HEAD is now at a5b219c Scoreboard formatting
[root@docker RootTheBox]# git pull
Already up-to-date.
```

Now I checked my version
```
[root@docker RootTheBox]# git log -1 --oneline
a5b219c Scoreboard formatting

```
I think it all worked ok but when I start the container and log into the scoreboard I see a warning message about git RTB updates.

**Comment by jeffg2k** [comment] 2020-01-27 03:41
Did you rebuild the docker container or delete recreate it?
I think it's `docker-compose build`

**Comment by jeremytourville** [comment] 2020-01-27 11:08
Ok, so I followed the steps from above plus added the `docker-compose build` command.  Now I can export which does fix the original problem I posted about.  :-)  Thank you very much!  I do still see the git update message when logged in though.

**Comment by jeffg2k** [comment] 2020-01-27 12:23
I'll check out the git update message.  That was created before we made the docker version and I'm not sure that it applies in a container.  It was designed for when you're running right from the git, not a docker build of it.  So, I might need to disable it if you're running from docker.

**Comment by jeremytourville** [comment] 2020-01-27 13:26
Yes, I am running from a Docker container.

**Comment by jeffg2k** [comment] 2020-01-28 02:10
Git status removed in docker https://github.com/moloch--/RootTheBox/commit/207372a266538283fbfd2d612e8807ab83a0dd98

**Closed by jeffg2k** 2020-01-28 02:10 UTC
Labels: reproduce issue
