### ISSUE TITLE
Scoreboard refresh

### ISSUE THREAD

**Issue by cgsilvers** [moloch--/RootTheBox#73] opened 2015-03-21 21:59 UTC
auto-refresh the scoreboard

**Comment by moloch--** [comment] 2015-03-21 22:00
The scoreboard is implemented with websockets and should update in realtime. However, if the server's `origin` isn't configured properly the websockets may fail to connect.

**Comment by cgsilvers** [comment] 2015-04-07 16:35
So, is it best to use the server´s IP address as the origin, or the FQDN?

**Comment by moloch--** [comment] 2015-04-07 17:23
Either should work, if you're hosting on a network with an Internet connect I'd recommend setting up a domain. Unfortunately, there's no great way to automatically detect this, by default the application will attempt to find it's local IP and use that, but it can't always tell which network interface/etc to use so it's best to set it manually.

**Comment by cgsilvers** [comment] 2015-04-08 11:30
OK.  I used the FQDN and we also tested using IE as well as Safari with no success.  How often should it refresh?

**Comment by kumux** [comment] 2015-10-13 01:48
Can't get the origin to change for accepting on port 80 when behind nginx proxy.  Error 400: Can "Upgrade" only to "WebSocket".

**Comment by mlaferrera** [comment] 2015-10-25 18:52
Adding 
proxy_set_header Host $host;

To the nginx configuration file under /scoreboard/wsocket and /notifications/wsocket solved the problem for me.

**Comment by jeffg2k** [comment] 2018-08-21 20:26
This may be a duplicate of #69.  It appears we now have "proxy_set_header Host $host;" at "/" in the nginx config.  Does this need to be added to /scoreboard/wsocket and /notifications/wsocket or is this issue resolved?

**Closed** 2018-09-10 20:48 UTC
Labels: bug
