### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by cgsilvers** [moloch--/RootTheBox#70] opened 2015-03-21 21:55 UTC
Error messages - numerous errors only presented a generic 404 page

**Comment by moloch--** [comment] 2015-03-21 21:57
Can you provide the log files, in a production deployment 500 errors are suppressed and instead return 404s, however the logs should still contain the full details.

**Comment by cgsilvers** [comment] 2015-04-07 16:42
Where can I find the logs you need to see?

**Comment by jeffg2k** [comment] 2018-08-22 14:57
In production deployment, the console running the rootthebox.py should display errors.  That could also be piped to a log file.  When in debug, I believe it displays the 500 with the error.  Since no actual bug is described in this issue and the generic 404 is by design, I'm going to close this issue.  Reopen if there is something that still needs to be addressed.

**Closed by jeffg2k** 2018-08-22 14:57 UTC
Labels: bug
