### ISSUE TITLE
RoottheBox Setup problem

### ISSUE THREAD

**Issue by hatim401** [moloch--/RootTheBox#61] opened 2015-01-13 05:11 UTC
Hi,

I am having a setup problem, please let me know the reason behind this.

Python Version : 2.7.3
If you have video tutorial for installation, please share.

 root@Kali~Home:~/RootTheBox-master# ./rootthebox.py --setup=prod
[I 150113 10:17:14 ConfigHelpers:9] Saving current config to: files/rootthebox.cfg
[_] 10:17:14 : Creating the database ...
[_] 10:17:14 : Bootstrapping the database ...
[?] Admin username: admin
[?] New Admin Password: 
[?] Confirm New Admin Password: 
Traceback (most recent call last):
  File "./rootthebox.py", line 447, in <module>
    setup()
  File "./rootthebox.py", line 68, in setup
    import setup.bootstrap
  File "/root/RootTheBox-master/setup/bootstrap.py", line 133, in <module>
    dbsession.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 205, in execute
  File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
sqlalchemy.exc.IntegrityError: (IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`rootthebox`.`user`, CONSTRAINT `user_ibfk_2` FOREIGN KEY (`theme_id`) REFERENCES `theme` (`id`))') 'INSERT INTO user (created, uuid, team_id, _avatar, _locked, last_login, logins, _handle, password, bank_password, theme_id, algorithm) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)' (datetime.datetime(2015, 1, 13, 10, 17, 38, 300696), 'ef632f77-8365-4f40-85a5-f8970f1b7f7d', None, None, 0, None, 0, 'admin', u'$p5k2$2bad$nrrD/1tX$VwtbalM60/KhhuQoyGFGzogs2espm9aM', None, 3, 'md5')

Thanks

**Comment by hatim401** [comment] 2015-01-16 05:57
Please let me how to rectify this error.

**Comment by moloch--** [comment] 2015-01-17 21:48
Can you post the versions numbers `./rootthebox.py --version` this is an odd issue.

**Comment by hatim401** [comment] 2015-01-18 16:07
![ubuntu](https://cloud.githubusercontent.com/assets/10497588/5793036/228a8890-9f5a-11e4-91c7-75abd85749a9.png)

**Comment by moloch--** [comment] 2015-01-18 22:07
Are you using MySQL or SQLite?

**Comment by hatim401** [comment] 2015-01-19 04:51
I am using MySQL as a database.

**Comment by moloch--** [comment] 2015-01-19 18:46
What version of Ubuntu (i'm not able to reproduce the error)?

**Comment by hatim401** [comment] 2015-01-20 11:04
Ubuntu version is 12.04.
I have tried this on Kali linux too, but shows same error.

CAn you send me your mail id so that i can send you the step which i followed, may be i was doing something wrong.

**Comment by hatim401** [comment] 2015-01-29 17:24
This is rootthebox.cfg file.

Please check all setting are correct or not.

# Last updated: 2015-01-22 22:57:20.004835

# [ Database ]
sql_database = "rootthebox"
sql_password = "rtb"
sql_port = 3306
sql_user = "rtb"
log_sql = False
sql_dialect = "mysql"
sql_host = "127.0.0.1"

# [ /Usr/Local/Lib/Python2.7/Dist-Packages/Tornado/Log.Py ]
logging = "info"
log_file_num_backups = 10
log_to_stderr = None
log_file_prefix = None
log_file_max_size = 100000000

# [ Recaptcha ]
use_recaptcha = True
recaptcha_api_key = "6LcJJ88SAAAAAFzcmQqDPWGKRQXmJ0DCiZoPWTZf"

# [ Cache ]
memcached = "127.0.0.1"
memcached_port = 11011

# [ Server ]
origin = "ws://localhost:8888"
admin_ips = ['127.0.0.1', '::1']
certfile = ""
listen_port = 8888
x_headers = False
ssl = False
session_age = 3600
session_regeneration_interval = 3600
keyfile = ""

# [ Application ]
share_dir = "./files/shares"
flag_attachment_dir = "./files/flag_attachments"
debug = False
source_code_market_dir = "./files/source_code_market"
avatar_dir = "./files/avatars"

# [ Game ]
use_black_market = True
use_bots = True
whitelist_box_ips = False
flag_value_decrease = 10
password_upgrade_cost = 1000
dynamic_flag_value = True
bribe_cost = 2500
max_password_length = 7
restrict_registration = False
botnet_db = "./files/botnet.db"
default_theme = "cyborg"
public_teams = True
game_name = "Root the Box"
history_snapshot_interval = 300000
bot_reward = 50
rank_by = "flags"
bot_reward_interval = 900000
max_team_size = 4

**Comment by BonJarber** [comment] 2015-02-13 05:37
I'm getting this same issue. Just tried installing on a fresh Debian box

**Comment by darkphantom934** [comment] 2015-03-11 03:57
Same here. Installing on Debian with Root the box v0.6.1, SQLAlchemy v0.9.9, and Torando v4.1.

**Comment by moloch--** [comment] 2015-03-11 16:58
I'm going to look into it this weekend.

**Comment by viris** [comment] 2015-03-16 10:37
Any news regarding this issue?

**Comment by meznak** [comment] 2015-04-04 06:02
I'm seeing this as well.
Ubuntu 12.04 3.2.0-79-generic-pae
Root the Box v0.6.1
SQL Alchemy v1.0.0b5
Torando v4.1

**Comment by meznak** [comment] 2015-05-30 04:26
After pulling the latest files (which caused a SQLAlchemy upgrade), I managed to get past this error.

It's fixed for me.

**Comment by jeffg2k** [comment] 2018-08-21 14:40
This appears to be fixed - so closing.  Reopen if needed.

**Closed by jeffg2k** 2018-08-21 14:40 UTC
Labels: bug

**Comment by NoobInTheNet** [comment] 2018-12-26 23:58
Hello everyone, after 3 years of this error that apparently was solved, I am having the same problem with the newest versions.

**System Information:**
Python 2.7.15 & 3.6.7 (_All modules were installed with PIP_)

**Python Installed Modules:**

**Error Message:**
  _File "./rootthebox.py", line 72, in setup
    import setup.bootstrap
  File "/home/FrameworkManager/RootTheBox/setup/bootstrap.py", line 78, in <module>
    dbsession.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 872, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
sqlalchemy.exc.IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'Bootstrap' for key '_name'") [S
QL: u'INSERT INTO theme (created, uuid, _name) VALUES (%s, %s, %s)'] [parameters: (datetime.datetime(2018, 12, 26, 23, 48,
 16, 149314), '0031c82e-91fa-4a85-bf83-9c7c271098f4', 'Bootstrap')] (Background on this error at: http://sqlalche.me/e/gkp
j)_

**Comment by NoobInTheNet** [comment] 2018-12-27 00:42
Okay, there has been a breakthrough, but I have not yet completely solved the error. Apparently when executing "./rootthebox.py --setup = prod" if a module is missing, after installing that module you must delete all the tables that have been created in the database and rerun the command.

After doing this, I get a new error, this time less long: 

[*] 00:37:40 : Creating the database ...
[*] 00:37:41 : Bootstrapping the database ...
[?] RootTheBox Admin Username: FrameworkAdmin
[?] New Admin Password: 
[?] Confirm New Admin Password: 
[I 181227 00:38:05 GameHistory:53] Loading game history from database ...
[I 181227 00:38:05 GameHistory:70] History load complete.
Traceback (most recent call last):
  File "./rootthebox.py", line 610, in <module>
    setup()
  File "./rootthebox.py", line 81, in setup
    update_db(False)
  File "/home/FrameworkManager/RootTheBox/handlers/__init__.py", line 272, in update_db
    alembic_cfg.set_main_option('sqlalchemy.url', str(db_connection))
  File "/usr/local/lib/python2.7/dist-packages/alembic/config.py", line 234, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "/usr/local/lib/python2.7/dist-packages/alembic/config.py", line 261, in set_section_option
    self.file_config.set(section, name, value)
  File "/usr/lib/python2.7/ConfigParser.py", line 752, in set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in 'mysql://FrameworkSQLManager:6qf%2B%2CLAh4Zdl@127.0.0.1/rootthebox' at positio
n 31

PD: Thank you very much for solving the first error. ;D

**Comment by jeffg2k** [comment] 2018-12-27 00:59
Looks like it's having a problem with the password.  It's added %2B%2C, encoding for "+,".  Apparently, it doesn't like % signs in the string.  I'll try to add something that will convert or work around this, but for now, try a password without those special characters.

**Comment by NoobInTheNet** [comment] 2018-12-27 01:07
All solved, I have removed the special characters and I have lengthened the password. No more errors at the moment: P

Thank you very much @jeffg2k ;D
