### ISSUE TITLE
Some enhancements  

### ISSUE THREAD

**Issue by nbven** [moloch--/RootTheBox#116] opened 2015-12-30 19:59 UTC
RFE: 1) No option to delete the team
         2) No option to set initial credit amount for all teams

**Comment by jeffg2k** [comment] 2018-08-21 16:29
The option to set the initial credit amount for teams has been added.
The option to delete a team is still on the todo, but changes were made that if there are no players in a team, RTB will hide that team from the players in most situations (might still be visible in the history graph).  https://github.com/moloch--/RootTheBox/commit/ce239c609ecf1cff65c7333ca7fd1e03b1067c18

Since the enhancement of deleting a team is a duplicate of #64 and tied into #130, I'm going to close this issue.

**Closed by jeffg2k** 2018-08-21 16:29 UTC
