### ISSUE TITLE
Registration time, support smtp, password recovery

### ISSUE THREAD

**Issue by cohux** [moloch--/RootTheBox#311] opened 2019-11-28 08:34 UTC
Support registration time, support smtp, password recovery ,Thanks developers

**Comment by jeffg2k** [comment] 2019-11-28 16:10
What do you mean by "registration time"?  By default, I think registration is open at any time and the game will start when you choose to start it.  Do you want the ability to disable the registration page until you're ready to start registration?

As for password recovery, I think that's a duplicate of https://github.com/moloch--/RootTheBox/issues/232  Help is wanted on that enhancement.  I'm not quite sure how to go about implementing a password recovery system, so it needs some research.

**Comment by alahammad** [comment] 2020-06-06 12:23
can we add sending reset password using fastmail this example : 

https://alexwlchan.net/2016/05/python-smtplib-and-fastmail/

**Comment by jeffg2k** [comment] 2021-01-31 01:16
Password Recovery was added, along with email validation.

**Closed by jeffg2k** 2021-01-31 01:16 UTC
Labels: enhancement
