### ISSUE TITLE
[Issue] Login error

### ISSUE THREAD

**Issue by noraj** [moloch--/RootTheBox#331] opened 2020-01-16 13:09 UTC
I'm encountering several different login issue.

1) A new user register himself with email only, he sets a new password. Then want to login and permission denied. I went in the admin panel reset the password to a new one and then it worked.
I created a second new user and it worked with the password he set during registration.
I created a third, no problem either. Seems hard to reproduce.

2) I logged in as admin, went in the admin settings and changed the admin password with the user form the default `rootthebox` to `mfJdh8n6SDWFhCj7NESy` successful. I logged out and tried to log in but impossible, either with the old or new password.

I first thought it was maybe due to #330 but after waiting a long time seems it's something different.

I had to attach to the container `docker exec -ti <dockername bash>` and then use teh recovery console `./rootthebox.py --recovery=True` and then change the admin password `chpass admin`.
By the way the recovery console has some commands that fail. see #332

**Comment by jeffg2k** [comment] 2020-01-16 21:33
The user handle and player name fields don't accept `@` as valid.  So not sure what you mean by email only.  Are you able to reproduce 2 as I haven't been able to yet.  I'll try in docker and see if I get a different result.

**Comment by jeffg2k** [comment] 2020-01-17 02:48
I loaded this up in the docker and was not able to reproduce the issue.

**Comment by noraj** [comment] 2020-01-17 10:00
> The user handle and player name fields don't accept `@` as valid. So not sure what you mean by email only. Are you able to reproduce 2 as I haven't been able to yet. I'll try in docker and see if I get a different result.

I wanted to say registration by email (not with token) but the handle and player name don't have a at sign in it.

Yeah, I can't reproduce right now, I'll see if I can with a new install.

**Comment by jeffg2k** [comment] 2020-01-30 02:24
I'm going to close this - if you run into the issue again and can provide any additional information, feel free to reopen.

**Closed by jeffg2k** 2020-01-30 02:24 UTC
Labels: reproduce issue
