### ISSUE TITLE
Only one attempt on Multiple Choice questions

### ISSUE THREAD

**Issue by Nebulat0r** [moloch--/RootTheBox#319] opened 2019-12-07 15:19 UTC
When setting Multiple Choice questions we noticed that if you got the question right first time you were ok.  

If you got the answer wrong you are not able to guess again as (even when selecting the right answer) you were told:

> "Information
> Duplicate submission - this answer has already been attempted by you. Try Again"

I think the MissionHandler.py is thinking that the game is in Team mode (it's not) and is invoking the code to prevent players resubmitting on top of each others answers.

**Comment by jeffg2k** [comment] 2019-12-07 18:50
@Nebulat0r I'm not able to reproduce that result.  The duplicate submission code applies in both individual and team mode.  It is called after the submission is deemed incorrect.  It then checks the player / team history to determine if that failed token has already been submitted (to determine if it should deduct penalty points for example).

Would be interesting to see in `MissionHandler.py` to add a print(token) after line 159 to see what you're receiving.  If you want to provide an example of the choices, I could try to recreate your situation to see if there is anything different about the tokens that might make it behave that way.

**Comment by jeffg2k** [comment] 2020-03-27 16:13
I think I know what happened here as I just pushed a fix https://github.com/moloch--/RootTheBox/commit/2d40f0c5214bfcc4771d10d71f7f1c5f9c8d336b for a multiple choice issue that would cause this.  The problem was if the token had a double quote in it, the token would be cropped prior to the first quote.  Thus if any answer had that same prefix, it would register as a duplicate answer.  When we inserted the token into the form value, it was not properly escaped, thus only getting the text until the first quote.  I've added a unique escape that is then converted back during submission.

**Closed by jeffg2k** 2020-03-27 16:13 UTC
Labels: can't reproduce
