### ISSUE TITLE
Level unlock issue and disappearing buttons

### ISSUE THREAD

**Issue by gekido2802** [moloch--/RootTheBox#112] opened 2015-10-25 03:43 UTC
Let's say I got a level which need 200$ to unlock but the team only have 100$, if they click on unlock, it will say that they don't have enough money and won't unlock it which is totally fine. 

The issue is when they reach that amount, it auto-unlock the level they pressed the button without removing the amount of money from the team's bank account and sometimes it seems to remove all the other unlock buttons.

**Comment by jeffg2k** [comment] 2018-09-01 01:00
I tested this and couldn't reproduce it, so I assume this was fixed at some point and the issue wasn't closed.  I tried to unlock and got the message that I didn't have enough.  When I reached enough money for the unlock, it didn't auto-unlock.  I had to try to unlock it again manually, which makes sense to me.  The level unlocked and funds were deducted.  So, I'm going to go ahead and close this issue.  If you're able to reproduce it with the latest code again, please reopen.

**Closed by jeffg2k** 2018-09-01 01:00 UTC
Labels: bug
